#!/usr/bin/env bun
/**
 * scripts/build.ts
 * --------------------------------------------------------------------------
 * Produces the published `bin` so `drawtui` can be launched from ANY package
 * manager / runtime (npm, pnpm, yarn, npx, bun, bunx) — and runs natively on
 * Node, so users who already have Node don't need to install Bun.
 *
 * Why a launcher instead of a plain bundle:
 *   @opentui/core renders through a native core reached over FFI. Under Bun
 *   that's `bun:ffi`; under Node it's the experimental `node:ffi` backend,
 *   which only exists when Node is started with `--experimental-ffi` (Node
 *   26.3+; some 26.x builds ship it early). That flag must be set at startup
 *   and can't be enabled afterwards, so the bin can't simply `import` the
 *   client — it has to re-exec Node with the flag.
 *
 * So we emit two files:
 *   • dist/client.js — the real CLI (src/cli.ts bundled to plain JS).
 *   • dist/cli.js    — a tiny Node-shebang launcher (the bin). It picks a
 *     runtime in this order:
 *       1. already under Bun (bunx) → import the client in-process,
 *       2. Node with node:ffi available → re-exec `node --experimental-ffi`,
 *       3. otherwise → fall back to Bun if installed, else explain the options.
 *
 * The result: `npx drawtui` / a global npm install run on Node alone, and only
 * old-Node-without-Bun setups are ever asked to upgrade Node or install Bun.
 * -------------------------------------------------------------------------- */

import { chmod } from "node:fs/promises";

const OUT_DIR = "dist";
const CLIENT_FILE = `${OUT_DIR}/client.js`;
const BIN_FILE = `${OUT_DIR}/cli.js`;

/* 1. Bundle the real CLI (transpile TS, inline local modules). @opentui/core
 *    ships prebuilt with a native core, so keep it external and resolve it from
 *    node_modules at runtime. */
const result = await Bun.build({
  entrypoints: ["src/cli.ts"],
  outdir: OUT_DIR,
  target: "node",
  format: "esm",
  external: ["@opentui/core"],
  naming: "client.js",
});

if (!result.success) {
  for (const log of result.logs) console.error(log);
  throw new Error("Build failed");
}

// Drop the source `#!/usr/bin/env bun` shebang from the client bundle — it is
// only ever imported or invoked via `bun dist/client.js`, never executed
// directly as a bin.
const clientSrc = await Bun.file(CLIENT_FILE).text();
if (clientSrc.startsWith("#!")) {
  await Bun.write(CLIENT_FILE, clientSrc.slice(clientSrc.indexOf("\n") + 1));
}

/* 2. Emit the launcher bin. */
const launcher = `#!/usr/bin/env node
/* Auto-generated by scripts/build.ts — do not edit. */
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const clientPath = fileURLToPath(new URL("./client.js", import.meta.url));
const args = process.argv.slice(2);
const isBun = typeof process !== "undefined" && process.versions && process.versions.bun;

if (isBun) {
  // Already under Bun (e.g. \`bunx\`): the native renderer reaches bun:ffi
  // directly, so just run the client in this process.
  await import("./client.js");
} else {
  // Under Node the renderer needs the experimental node:ffi backend, which only
  // exists when Node is started with --experimental-ffi. A startup flag can't be
  // added after boot, so probe whether this Node supports it, then re-exec this
  // same Node binary with the flag set.
  const nodeHasFfi =
    spawnSync(process.execPath, ["--experimental-ffi", "-e", "require('node:ffi')"], {
      stdio: "ignore",
    }).status === 0;

  if (nodeHasFfi) {
    const res = spawnSync(
      process.execPath,
      ["--experimental-ffi", "--disable-warning=ExperimentalWarning", clientPath, ...args],
      { stdio: "inherit" },
    );
    if (res.error) throw res.error;
    process.exit(res.status ?? 0);
  } else {
    // This Node is too old for node:ffi — fall back to Bun if it's installed.
    const res = spawnSync("bun", [clientPath, ...args], { stdio: "inherit" });
    if (res.error) {
      if (res.error.code === "ENOENT") {
        console.error(
          "drawtui renders its terminal UI through a native core over FFI, which\\n" +
            "needs one of:\\n" +
            "  - Node.js 26.3+ (it's launched automatically with --experimental-ffi), or\\n" +
            "  - Bun.\\n\\n" +
            "Your Node.js (v" + process.versions.node + ") is too old for node:ffi.\\n" +
            "Upgrade Node from https://nodejs.org, or install Bun:\\n" +
            "  curl -fsSL https://bun.sh/install | bash\\n",
        );
        process.exit(1);
      }
      throw res.error;
    }
    process.exit(res.status ?? 0);
  }
}
`;

await Bun.write(BIN_FILE, launcher);
await chmod(BIN_FILE, 0o755);

console.log(
  `Built ${BIN_FILE} (launcher) + ${CLIENT_FILE} (${(Bun.file(CLIENT_FILE).size / 1024).toFixed(1)} KB)`,
);
