#!/usr/bin/env bun
/**
 * scripts/build.ts
 * --------------------------------------------------------------------------
 * Produces the published `bin` so `drawtui` can be launched from ANY package
 * manager / runtime (npm, pnpm, yarn, npx, bun, bunx) — even though the actual
 * terminal renderer only works under Bun.
 *
 * Why a launcher instead of a plain bundle:
 *   @opentui/core renders through a native core reached over FFI. Under Bun
 *   that's `bun:ffi`; under Node it needs `node:ffi`, which stock Node does not
 *   ship — so the renderer simply cannot initialize on Node. Pointing the bin
 *   straight at JS with a `node` shebang therefore *runs* under Node but dies
 *   with "OpenTUI native FFI is not available for this runtime yet".
 *
 * So we emit two files:
 *   • dist/client.js — the real CLI (src/cli.ts bundled to plain JS).
 *   • dist/cli.js    — a tiny Node-shebang launcher (the bin). If it's already
 *     running under Bun it imports the client in-process; otherwise it re-execs
 *     the client under `bun`, and if Bun isn't installed prints how to get it.
 *
 * This makes `npx drawtui` and a global npm install work transparently
 * whenever Bun is present, instead of failing with an opaque native error.
 * -------------------------------------------------------------------------- */

import { chmod } from "node:fs/promises";

const OUT_DIR = "dist";
const CLIENT_FILE = `${OUT_DIR}/client.js`;
const BIN_FILE = `${OUT_DIR}/cli.js`;

/* 1. Bundle the real CLI (transpile TS, inline local modules). @opentui/core
 *    ships prebuilt with a native core, so keep it external and resolve it from
 *    node_modules at runtime. */
const result = await Bun.build({
  entrypoints: ["src/cli.ts"],
  outdir: OUT_DIR,
  target: "node",
  format: "esm",
  external: ["@opentui/core"],
  naming: "client.js",
});

if (!result.success) {
  for (const log of result.logs) console.error(log);
  throw new Error("Build failed");
}

// Drop the source `#!/usr/bin/env bun` shebang from the client bundle — it is
// only ever imported or invoked via `bun dist/client.js`, never executed
// directly as a bin.
const clientSrc = await Bun.file(CLIENT_FILE).text();
if (clientSrc.startsWith("#!")) {
  await Bun.write(CLIENT_FILE, clientSrc.slice(clientSrc.indexOf("\n") + 1));
}

/* 2. Emit the launcher bin. */
const launcher = `#!/usr/bin/env node
/* Auto-generated by scripts/build.ts — do not edit. */
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const clientPath = fileURLToPath(new URL("./client.js", import.meta.url));

// Already under Bun (e.g. \`bunx\`)? Run the client in-process — its native
// renderer can reach bun:ffi directly.
if (typeof process !== "undefined" && process.versions && process.versions.bun) {
  await import("./client.js");
} else {
  // Under Node/npm/pnpm/yarn the OpenTUI renderer can't initialize (no
  // node:ffi), so re-exec the client under Bun.
  const res = spawnSync("bun", [clientPath, ...process.argv.slice(2)], {
    stdio: "inherit",
  });
  if (res.error) {
    if (res.error.code === "ENOENT") {
      console.error(
        "drawtui renders its terminal UI through Bun's native FFI, which isn't\\n" +
          "available on Node yet — so it needs Bun installed to run.\\n\\n" +
          "Install Bun (one line), then run drawtui again:\\n" +
          "  curl -fsSL https://bun.sh/install | bash\\n\\n" +
          "More options: https://bun.sh/docs/installation",
      );
      process.exit(1);
    }
    throw res.error;
  }
  process.exit(res.status ?? 0);
}
`;

await Bun.write(BIN_FILE, launcher);
await chmod(BIN_FILE, 0o755);

console.log(
  `Built ${BIN_FILE} (launcher) + ${CLIENT_FILE} (${(Bun.file(CLIENT_FILE).size / 1024).toFixed(1)} KB)`,
);
